// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/ai-advisor" | "/crypto" | "/login" | "/method" | "/precious-metals" | "/register" | "/strategy/[ticker]" | "/strategy/[ticker]/asset/[assetTicker]" | "/tr-stocks" | "/us-stocks"
type AppRouteHandlerRoutes = "/api/ai-advisor" | "/api/assets" | "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/best-opportunities" | "/api/market-data" | "/api/recommendations" | "/api/search" | "/api/strategy/[ticker]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/ai-advisor": {}
  "/api/ai-advisor": {}
  "/api/assets": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/register": {}
  "/api/best-opportunities": {}
  "/api/market-data": {}
  "/api/recommendations": {}
  "/api/search": {}
  "/api/strategy/[ticker]": { "ticker": string; }
  "/crypto": {}
  "/login": {}
  "/method": {}
  "/precious-metals": {}
  "/register": {}
  "/strategy/[ticker]": { "ticker": string; }
  "/strategy/[ticker]/asset/[assetTicker]": { "ticker": string; "assetTicker": string; }
  "/tr-stocks": {}
  "/us-stocks": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
