var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/opportunities/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b198e079._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_bb5bf2ac._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fa65278f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6550089d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_19f292b3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_opportunities_page_actions_a306cede.js")
R.m(98840)
module.exports=R.m(98840).exports
