var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/strategy/[ticker]/asset/[assetTicker]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1f989645._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_3952cced._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fa65278f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6550089d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_19f292b3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/ce889_server_app_strategy_[ticker]_asset_[assetTicker]_page_actions_b5315942.js")
R.m(43457)
module.exports=R.m(43457).exports
